spring:
  application:
    name: bomber-dino-backend

server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true

logging:
  level:
    root: INFO
    com.arsw.bomberdino: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://bomber-dino-frontend-prod.azurewebsites.net}

websocket:
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:https://bomber-dino-frontend-prod.azurewebsites.net}
  message-size-limit: 65536
  send-buffer-size: 524288
  send-time-limit: 20000
